### ISSUE TITLE
Asking about one line of code, thanks

### ISSUE THREAD

**Issue by heybran** [beautifulcoder/framework-less-web-components#1]
Hi Camilo,

I've been reading your framework-less web components repo for a few days now, if possible, may I pick your brain about one line of code in your repo? I notice that you return an arrow function from `proxy.addChangeListener()`, wondering if you can be so kind as to help me understand a bit more that function? Sorry if this is not the correct way to reach out to you.

```javascript
// model/observable.js
const cloneDeep = x => JSON.parse(JSON.stringify(x))
const freeze = state => Object.freeze(cloneDeep(state))

export default initialState => {
  let listeners = []

  const proxy = new Proxy(cloneDeep(initialState), {
    set: (target, name, value) => {
      target[name] = value
      listeners.forEach(l => l(freeze(proxy)))
      return true
    }
  })

  proxy.addChangeListener = cb => {
    listeners.push(cb)
    cb(freeze(proxy))
    // I was referencing to this return below :)
    return () =>
      listeners = listeners.filter(el => el !== cb)
  }

  return proxy
}
```

https://github.com/beautifulcoder/framework-less-web-components/blob/fe837d52f9e46dfe21d61017489956cf1f1f1e16/model/observable.js#L18

Thanks,
Brandon

**Comment by beautifulcoder** [comment]
Hey Brandon,

This is a good question. It might be used by the `ObservableElement` to keep track of the listener in case you want to delete it later. It's a pattern borrowed from redux. I think it is safe to delete since it's not being used.

Basically, this is how you'd register/unregister the listener:

```javascript
window
  .applicationContext
  .observableState
  .addChangeListener(state => {
    this.authors = state.authors
    this.currentFilter = state.currentFilter
  })() // unregister
```

Like I said, it's not used at all, as far as I can tell. Likely it is safe to nuke.

**Comment by heybran** [comment]
Awesome, thanks a lot! Our company currently uses `CustomEvent` to manage component state, which is not ideal. It's such a pleasure finding a repo this yours that focuses on components state. 

Btw, I included two of your posts about web components from sitepoint in this repo of mine, hope you don't mind that :)
https://github.com/iambran/web-components-resources

Actually, it's my first issue on GitHub, not sure if I should close this issue now? Thanks
